### PR TITLE
Specify whether to fetch album artwork in `getAlbums()`

### PR DESCRIPTION
**Pull request by thebradbain**
As laid out in the roadmap

### CODE REVIEW

**Comment by kadiks** [comment]
Dude, you rock.

I'll be testing it over the weekend!

**Comment by thebradbain** [comment]
Thanks! Was just a quick fix I made for my own personal project, thought I'd contribute upstream. Definitely let me know if there's anything you'd like me to change.

**Comment by thebradbain** [comment]
Actually - it definitely looks like I was operating on an older commit than previously made to the repo. The changes should just be contained to fetchAlbums.

**Comment by thebradbain** [comment]
See #16 for updated commit and further updates. I recommend closing this commit.

**Pull request closed without merging**
